services:
  download_producer:
    build: .
    command: python download_producer.py
    networks:
      - mynet

  warc_downloader:
    build: .
    command: python warc_downloader.py
    networks:
      - mynet

  vectorizer_consumer:
    build: .
    command: python vectorizer_consumer.py
    networks:
      - mynet

  indexer_consumer:
    build: .
    command: python indexer_consumer.py
    networks:
      - mynet

networks:
  mynet:
