services:
  postgres:
    image: postgres:latest
    container_name: postgres_ysearch
    environment:
      POSTGRES_DB: ysearch
      POSTGRES_USER: ysearch
      POSTGRES_PASSWORD: ysearch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: