services:
  postgres:
    image: postgres:latest
    container_name: postgres_ysearch
    environment:
      POSTGRES_DB: ysearch
      POSTGRES_USER: ysearch
      POSTGRES_PASSWORD: ysearch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port for RabbitMQ protocol
      - "15672:15672" # Port for RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  postgres_data:
  rabbitmq_data: